# Generated by Django 4.1.3 on 2023-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0002_codelogin_delete_user_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelogin',
            name='username',
            field=models.CharField(max_length=11),
        ),
    ]
