# Generated by Django 4.1.3 on 2023-01-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0003_alter_codelogin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codelogin',
            name='verification_code',
            field=models.CharField(max_length=6),
        ),
    ]
